#pragma once

#define IDI_ICON_APP 100

#define IDS_CONFIG_TITLE 200
#define IDS_RELOAD 201
#define IDS_KEYBOARD_LAYOUT 202
#define IDS_INPUT_MODE 203
#define IDS_CANDIDATE_WINDOW 204
#define IDS_VERTICAL 205
#define IDS_HORIZONTAL 206
#define IDS_CANDIDATE_KEYS 207
#define IDS_CANDIDATES_PER_PAGE 208
#define IDS_SELECTION_CURSOR 209
#define IDS_SELECT_BEFORE 210
#define IDS_SELECT_AFTER 211
#define IDS_MOVE_CURSOR 212
#define IDS_INPUT_BEHAVIOR 213
#define IDS_SHIFT_LETTER_UPPER 214
#define IDS_SHIFT_LETTER_LOWER 215
#define IDS_ESC_CLEAR 216
#define IDS_SHIFT_ENTER 217
#define IDS_CTRL_ENTER 218
#define IDS_CANDIDATES_PUNCTUATION 219
#define IDS_REPEATED_PUNCTUATION 220
#define IDS_CHOOSE_SPACE 221

#define IDS_LAYOUT_STANDARD 222
#define IDS_LAYOUT_ETEN 223
#define IDS_LAYOUT_HSU 224
#define IDS_LAYOUT_ETEN26 225
#define IDS_LAYOUT_HANYUPINYIN 226
#define IDS_LAYOUT_IBM 227

#define IDS_MODE_MCBOPOMOFO 228
#define IDS_MODE_PLAIN_BOPOMOFO 229

#define IDS_CTRL_ENTER_DISABLED 230
#define IDS_CTRL_ENTER_BPMF_READING 231
#define IDS_CTRL_ENTER_HTML_RUBY 232
#define IDS_CTRL_ENTER_HANYU_PINYIN 233
#define IDS_SELECTION_ACTION 234
#define IDS_SELECTION_ACTION_NONE 235
#define IDS_SELECTION_ACTION_JK 236
#define IDS_SELECTION_ACTION_HL 237
#define IDS_CANDIDATE_PRESENTATION 238
#define IDS_CANDIDATE_FONT_SIZE 239
#define IDS_SHIFT_TOGGLE 240
#define IDS_SHIFT_TOGGLE_OPEN_CLOSE 241
#define IDS_ERROR_BEEP 242
#define IDS_MANUAL_LINK 243
#define IDS_PROJECT_HOMEPAGE 244
#define IDS_MODE_MCBOPOMOFO_AUTO 245
#define IDS_MODE_PLAIN_BOPOMOFO_MANUAL 246
#define IDS_SHIFT_LETTER 247
#define IDS_CTRL_ENTER_TAIWAN_BRAILLE_UNICODE 248
#define IDS_CTRL_ENTER_TAIWAN_BRAILLE_ASCII 249
